//! Static lookup tables for math command mapping between LaTeX, Typst, and Unicode.

use std::collections::HashMap;
use std::sync::LazyLock;

/// Simple 1:1 LaTeX command renames to Typst (backslash already stripped).
pub static LATEX_TO_TYPST_COMMANDS: LazyLock<HashMap<&'static str, &'static str>> =
    LazyLock::new(|| {
        HashMap::from([
            // Greek lowercase
            ("alpha", "alpha"),
            ("beta", "beta"),
            ("gamma", "gamma"),
            ("delta", "delta"),
            ("epsilon", "epsilon"),
            ("varepsilon", "epsilon.alt"),
            ("zeta", "zeta"),
            ("eta", "eta"),
            ("theta", "theta"),
            ("vartheta", "theta.alt"),
            ("iota", "iota"),
            ("kappa", "kappa"),
            ("lambda", "lambda"),
            ("mu", "mu"),
            ("nu", "nu"),
            ("xi", "xi"),
            ("pi", "pi"),
            ("varpi", "pi.alt"),
            ("rho", "rho"),
            ("varrho", "rho.alt"),
            ("sigma", "sigma"),
            ("varsigma", "sigma.alt"),
            ("tau", "tau"),
            ("upsilon", "upsilon"),
            ("phi", "phi"),
            ("varphi", "phi.alt"),
            ("chi", "chi"),
            ("psi", "psi"),
            ("omega", "omega"),
            // Greek uppercase
            ("Gamma", "Gamma"),
            ("Delta", "Delta"),
            ("Theta", "Theta"),
            ("Lambda", "Lambda"),
            ("Xi", "Xi"),
            ("Pi", "Pi"),
            ("Sigma", "Sigma"),
            ("Upsilon", "Upsilon"),
            ("Phi", "Phi"),
            ("Psi", "Psi"),
            ("Omega", "Omega"),
            // Operators
            ("sum", "sum"),
            ("prod", "product"),
            ("int", "integral"),
            ("iint", "integral.double"),
            ("iiint", "integral.triple"),
            ("oint", "integral.cont"),
            ("lim", "lim"),
            ("sup", "sup"),
            ("inf", "inf"),
            ("max", "max"),
            ("min", "min"),
            ("sin", "sin"),
            ("cos", "cos"),
            ("tan", "tan"),
            ("arcsin", "arcsin"),
            ("arccos", "arccos"),
            ("arctan", "arctan"),
            ("sinh", "sinh"),
            ("cosh", "cosh"),
            ("tanh", "tanh"),
            ("log", "log"),
            ("ln", "ln"),
            ("exp", "exp"),
            ("det", "det"),
            ("deg", "deg"),
            ("dim", "dim"),
            ("ker", "ker"),
            ("gcd", "gcd"),
            ("lcm", "lcm"),
            ("Pr", "Pr"),
            ("hom", "hom"),
            // Arrows
            ("to", "arrow.r"),
            ("rightarrow", "arrow.r"),
            ("leftarrow", "arrow.l"),
            ("Rightarrow", "arrow.r.double"),
            ("Leftarrow", "arrow.l.double"),
            ("leftrightarrow", "arrow.l.r"),
            ("Leftrightarrow", "arrow.l.r.double"),
            ("implies", "arrow.r.double"),
            ("iff", "arrow.l.r.double"),
            ("uparrow", "arrow.t"),
            ("downarrow", "arrow.b"),
            ("Uparrow", "arrow.t.double"),
            ("Downarrow", "arrow.b.double"),
            ("nearrow", "arrow.tr"),
            ("searrow", "arrow.br"),
            ("swarrow", "arrow.bl"),
            ("nwarrow", "arrow.tl"),
            ("mapsto", "arrow.r.bar"),
            ("longmapsto", "arrow.r.long.bar"),
            ("hookleftarrow", "arrow.l.hook"),
            ("hookrightarrow", "arrow.r.hook"),
            ("leftharpoonup", "harpoon.lt"),
            ("rightharpoonup", "harpoon.rt"),
            // Relations
            ("leq", "lt.eq"),
            ("geq", "gt.eq"),
            ("le", "lt.eq"),
            ("ge", "gt.eq"),
            ("neq", "eq.not"),
            ("ne", "eq.not"),
            ("in", "in"),
            ("notin", "in.not"),
            ("subset", "subset"),
            ("supset", "supset"),
            ("subseteq", "subset.eq"),
            ("supseteq", "supset.eq"),
            ("equiv", "equiv"),
            ("approx", "approx"),
            ("sim", "tilde.op"),
            ("simeq", "tilde.eq"),
            ("cong", "tilde.eqq"),
            ("propto", "prop"),
            ("perp", "perp"),
            ("parallel", "parallel"),
            ("mid", "divides"),
            ("nmid", "divides.not"),
            ("ll", "lt.double"),
            ("gg", "gt.double"),
            ("prec", "prec"),
            ("succ", "succ"),
            ("preceq", "prec.eq"),
            ("succeq", "succ.eq"),
            // Misc symbols
            ("infty", "infinity"),
            ("partial", "partial"),
            ("nabla", "nabla"),
            ("times", "times"),
            ("cdot", "dot.op"),
            ("circ", "compose"),
            ("bullet", "bullet"),
            ("star", "star"),
            ("oplus", "plus.circle"),
            ("ominus", "minus.circle"),
            ("otimes", "times.circle"),
            ("oslash", "div.circle"),
            ("odot", "dot.circle"),
            ("cap", "sect"),
            ("cup", "union"),
            ("bigcap", "sect.big"),
            ("bigcup", "union.big"),
            ("setminus", "without"),
            ("emptyset", "emptyset"),
            ("forall", "forall"),
            ("exists", "exists"),
            ("nexists", "exists.not"),
            ("neg", "not"),
            ("lnot", "not"),
            ("land", "and"),
            ("lor", "or"),
            ("wedge", "and"),
            ("vee", "or"),
            ("top", "top"),
            ("bot", "bot"),
            ("angle", "angle"),
            ("triangle", "triangle.t"),
            ("square", "square"),
            ("diamond", "diamond"),
            ("pm", "plus.minus"),
            ("mp", "minus.plus"),
            ("div", "div"),
            ("ldots", "dots.h"),
            ("cdots", "dots.c"),
            ("vdots", "dots.v"),
            ("ddots", "dots.down"),
            ("ell", "ell"),
            ("hbar", "planck.reduce"),
            ("Re", "Re"),
            ("Im", "Im"),
            ("aleph", "aleph"),
            ("wp", "weierp"),
            ("prime", "prime"),
            ("dagger", "dagger"),
            ("ddagger", "dagger.double"),
            ("sharp", "sharp"),
            ("flat", "flat"),
            ("natural", "natural"),
            ("clubsuit", "suit.club"),
            ("diamondsuit", "suit.diamond"),
            ("heartsuit", "suit.heart"),
            ("spadesuit", "suit.spade"),
            // Brackets
            ("langle", "angle.l"),
            ("rangle", "angle.r"),
            ("lceil", "ceil.l"),
            ("rceil", "ceil.r"),
            ("lfloor", "floor.l"),
            ("rfloor", "floor.r"),
            // Spacing
            ("quad", "quad"),
            ("qquad", "wide"),
            (",", "thin"),
            (";", "med"),
            ("!", "negthin"),
        ])
    });

/// LaTeX commands that take `{arg}` and become `func(arg)` in Typst.
pub static LATEX_TO_TYPST_FUNCTIONS: LazyLock<HashMap<&'static str, &'static str>> =
    LazyLock::new(|| {
        HashMap::from([
            // Accents / decorations
            ("hat", "hat"),
            ("bar", "overline"),
            ("vec", "arrow"),
            ("tilde", "tilde"),
            ("dot", "dot"),
            ("ddot", "dot.double"),
            ("acute", "acute"),
            ("grave", "grave"),
            ("breve", "breve"),
            ("check", "caron"),
            ("widehat", "hat"),
            ("widetilde", "tilde"),
            // Font commands
            ("mathbf", "bold"),
            ("mathit", "italic"),
            ("mathrm", "upright"),
            ("mathcal", "cal"),
            ("mathbb", "bb"),
            ("mathfrak", "frak"),
            ("mathsf", "sans"),
            ("mathtt", "mono"),
            // Stretch decorations
            ("overline", "overline"),
            ("underline", "underline"),
            ("overbrace", "overbrace"),
            ("underbrace", "underbrace"),
            ("sqrt", "sqrt"),
        ])
    });

/// LaTeX environment names → (Typst function name, delimiter argument).
pub static LATEX_ENV_TO_TYPST: LazyLock<HashMap<&'static str, (&'static str, &'static str)>> =
    LazyLock::new(|| {
        HashMap::from([
            ("pmatrix", ("mat", "\"(\"")),
            ("bmatrix", ("mat", "\"[\"")),
            ("Bmatrix", ("mat", "\"{\"")),
            ("vmatrix", ("mat", "\"|\"")),
            ("Vmatrix", ("mat", "\"‖\"")),
            ("matrix", ("mat", "")),
            ("smallmatrix", ("mat", "")),
            ("cases", ("cases", "")),
            ("aligned", ("aligned", "")),
            ("align", ("aligned", "")),
            ("gathered", ("gathered", "")),
            ("gather", ("gathered", "")),
            ("split", ("aligned", "")),
            ("multline", ("aligned", "")),
            ("array", ("mat", "")),
        ])
    });

/// `\mathbb{X}` letter → Typst shorthand.
pub static MATHBB_TO_TYPST: LazyLock<HashMap<&'static str, &'static str>> = LazyLock::new(|| {
    HashMap::from([
        ("R", "RR"),
        ("N", "NN"),
        ("Z", "ZZ"),
        ("Q", "QQ"),
        ("C", "CC"),
        ("H", "HH"),
        ("P", "PP"),
        ("1", "bb(1)"),
    ])
});

/// LaTeX command → Unicode character (for MathML / plain-text output).
pub static LATEX_TO_UNICODE: LazyLock<HashMap<&'static str, &'static str>> = LazyLock::new(|| {
    HashMap::from([
        // Greek lowercase
        ("alpha", "\u{03B1}"),
        ("beta", "\u{03B2}"),
        ("gamma", "\u{03B3}"),
        ("delta", "\u{03B4}"),
        ("epsilon", "\u{03B5}"),
        ("varepsilon", "\u{03B5}"),
        ("zeta", "\u{03B6}"),
        ("eta", "\u{03B7}"),
        ("theta", "\u{03B8}"),
        ("vartheta", "\u{03D1}"),
        ("iota", "\u{03B9}"),
        ("kappa", "\u{03BA}"),
        ("lambda", "\u{03BB}"),
        ("mu", "\u{03BC}"),
        ("nu", "\u{03BD}"),
        ("xi", "\u{03BE}"),
        ("pi", "\u{03C0}"),
        ("varpi", "\u{03D6}"),
        ("rho", "\u{03C1}"),
        ("varrho", "\u{03F1}"),
        ("sigma", "\u{03C3}"),
        ("varsigma", "\u{03C2}"),
        ("tau", "\u{03C4}"),
        ("upsilon", "\u{03C5}"),
        ("phi", "\u{03D5}"),
        ("varphi", "\u{03C6}"),
        ("chi", "\u{03C7}"),
        ("psi", "\u{03C8}"),
        ("omega", "\u{03C9}"),
        // Greek uppercase
        ("Gamma", "\u{0393}"),
        ("Delta", "\u{0394}"),
        ("Theta", "\u{0398}"),
        ("Lambda", "\u{039B}"),
        ("Xi", "\u{039E}"),
        ("Pi", "\u{03A0}"),
        ("Sigma", "\u{03A3}"),
        ("Upsilon", "\u{03A5}"),
        ("Phi", "\u{03A6}"),
        ("Psi", "\u{03A8}"),
        ("Omega", "\u{03A9}"),
        // Common symbols
        ("infty", "\u{221E}"),
        ("partial", "\u{2202}"),
        ("nabla", "\u{2207}"),
        ("sum", "\u{2211}"),
        ("prod", "\u{220F}"),
        ("int", "\u{222B}"),
        ("iint", "\u{222C}"),
        ("iiint", "\u{222D}"),
        ("oint", "\u{222E}"),
        ("times", "\u{00D7}"),
        ("div", "\u{00F7}"),
        ("pm", "\u{00B1}"),
        ("mp", "\u{2213}"),
        ("cdot", "\u{22C5}"),
        ("circ", "\u{2218}"),
        ("bullet", "\u{2022}"),
        ("star", "\u{22C6}"),
        ("oplus", "\u{2295}"),
        ("ominus", "\u{2296}"),
        ("otimes", "\u{2297}"),
        ("oslash", "\u{2298}"),
        ("odot", "\u{2299}"),
        // Set / logic
        ("cap", "\u{2229}"),
        ("cup", "\u{222A}"),
        ("emptyset", "\u{2205}"),
        ("forall", "\u{2200}"),
        ("exists", "\u{2203}"),
        ("neg", "\u{00AC}"),
        ("land", "\u{2227}"),
        ("lor", "\u{2228}"),
        ("top", "\u{22A4}"),
        ("bot", "\u{22A5}"),
        ("setminus", "\u{2216}"),
        // Arrows
        ("to", "\u{2192}"),
        ("rightarrow", "\u{2192}"),
        ("leftarrow", "\u{2190}"),
        ("Rightarrow", "\u{21D2}"),
        ("Leftarrow", "\u{21D0}"),
        ("leftrightarrow", "\u{2194}"),
        ("Leftrightarrow", "\u{21D4}"),
        ("implies", "\u{21D2}"),
        ("iff", "\u{21D4}"),
        ("uparrow", "\u{2191}"),
        ("downarrow", "\u{2193}"),
        ("mapsto", "\u{21A6}"),
        ("nearrow", "\u{2197}"),
        ("searrow", "\u{2198}"),
        ("swarrow", "\u{2199}"),
        ("nwarrow", "\u{2196}"),
        // Relations
        ("leq", "\u{2264}"),
        ("geq", "\u{2265}"),
        ("le", "\u{2264}"),
        ("ge", "\u{2265}"),
        ("neq", "\u{2260}"),
        ("ne", "\u{2260}"),
        ("in", "\u{2208}"),
        ("notin", "\u{2209}"),
        ("subset", "\u{2282}"),
        ("supset", "\u{2283}"),
        ("subseteq", "\u{2286}"),
        ("supseteq", "\u{2287}"),
        ("equiv", "\u{2261}"),
        ("approx", "\u{2248}"),
        ("sim", "\u{223C}"),
        ("simeq", "\u{2243}"),
        ("cong", "\u{2245}"),
        ("propto", "\u{221D}"),
        ("perp", "\u{22A5}"),
        ("parallel", "\u{2225}"),
        ("ll", "\u{226A}"),
        ("gg", "\u{226B}"),
        ("prec", "\u{227A}"),
        ("succ", "\u{227B}"),
        // Misc
        ("ldots", "\u{2026}"),
        ("cdots", "\u{22EF}"),
        ("vdots", "\u{22EE}"),
        ("ddots", "\u{22F1}"),
        ("ell", "\u{2113}"),
        ("hbar", "\u{210F}"),
        ("Re", "\u{211C}"),
        ("Im", "\u{2111}"),
        ("aleph", "\u{2135}"),
        ("prime", "\u{2032}"),
        ("dagger", "\u{2020}"),
        ("ddagger", "\u{2021}"),
        ("angle", "\u{2220}"),
        ("langle", "\u{27E8}"),
        ("rangle", "\u{27E9}"),
        ("lceil", "\u{2308}"),
        ("rceil", "\u{2309}"),
        ("lfloor", "\u{230A}"),
        ("rfloor", "\u{230B}"),
    ])
});

/// Typst math identifiers → LaTeX command names (reverse mapping).
pub static TYPST_TO_LATEX_COMMANDS: LazyLock<HashMap<&'static str, &'static str>> =
    LazyLock::new(|| {
        HashMap::from([
            // Greek
            ("alpha", "alpha"),
            ("beta", "beta"),
            ("gamma", "gamma"),
            ("delta", "delta"),
            ("epsilon", "epsilon"),
            ("zeta", "zeta"),
            ("eta", "eta"),
            ("theta", "theta"),
            ("iota", "iota"),
            ("kappa", "kappa"),
            ("lambda", "lambda"),
            ("mu", "mu"),
            ("nu", "nu"),
            ("xi", "xi"),
            ("pi", "pi"),
            ("rho", "rho"),
            ("sigma", "sigma"),
            ("tau", "tau"),
            ("upsilon", "upsilon"),
            ("phi", "phi"),
            ("chi", "chi"),
            ("psi", "psi"),
            ("omega", "omega"),
            ("Gamma", "Gamma"),
            ("Delta", "Delta"),
            ("Theta", "Theta"),
            ("Lambda", "Lambda"),
            ("Xi", "Xi"),
            ("Pi", "Pi"),
            ("Sigma", "Sigma"),
            ("Upsilon", "Upsilon"),
            ("Phi", "Phi"),
            ("Psi", "Psi"),
            ("Omega", "Omega"),
            // Operators
            ("sum", "sum"),
            ("product", "prod"),
            ("integral", "int"),
            ("lim", "lim"),
            ("sup", "sup"),
            ("inf", "inf"),
            ("max", "max"),
            ("min", "min"),
            ("sin", "sin"),
            ("cos", "cos"),
            ("tan", "tan"),
            ("arcsin", "arcsin"),
            ("arccos", "arccos"),
            ("arctan", "arctan"),
            ("sinh", "sinh"),
            ("cosh", "cosh"),
            ("tanh", "tanh"),
            ("log", "log"),
            ("ln", "ln"),
            ("exp", "exp"),
            ("det", "det"),
            ("gcd", "gcd"),
            // Arrows
            ("arrow.r", "rightarrow"),
            ("arrow.l", "leftarrow"),
            ("arrow.r.double", "Rightarrow"),
            ("arrow.l.double", "Leftarrow"),
            ("arrow.l.r", "leftrightarrow"),
            ("arrow.l.r.double", "Leftrightarrow"),
            ("arrow.t", "uparrow"),
            ("arrow.b", "downarrow"),
            ("arrow.r.bar", "mapsto"),
            // Relations
            ("lt.eq", "leq"),
            ("gt.eq", "geq"),
            ("eq.not", "neq"),
            ("in", "in"),
            ("in.not", "notin"),
            ("subset", "subset"),
            ("supset", "supset"),
            ("subset.eq", "subseteq"),
            ("supset.eq", "supseteq"),
            ("equiv", "equiv"),
            ("approx", "approx"),
            ("tilde.op", "sim"),
            ("tilde.eq", "simeq"),
            ("prop", "propto"),
            ("perp", "perp"),
            ("parallel", "parallel"),
            ("lt.double", "ll"),
            ("gt.double", "gg"),
            ("prec", "prec"),
            ("succ", "succ"),
            // Misc
            ("infinity", "infty"),
            ("partial", "partial"),
            ("nabla", "nabla"),
            ("times", "times"),
            ("dot.op", "cdot"),
            ("compose", "circ"),
            ("plus.circle", "oplus"),
            ("times.circle", "otimes"),
            ("sect", "cap"),
            ("union", "cup"),
            ("emptyset", "emptyset"),
            ("forall", "forall"),
            ("exists", "exists"),
            ("not", "neg"),
            ("and", "land"),
            ("or", "lor"),
            ("top", "top"),
            ("bot", "bot"),
            ("without", "setminus"),
            ("plus.minus", "pm"),
            ("minus.plus", "mp"),
            ("div", "div"),
            ("dots.h", "ldots"),
            ("dots.c", "cdots"),
            ("dots.v", "vdots"),
            ("dots.down", "ddots"),
            ("ell", "ell"),
            ("planck.reduce", "hbar"),
            ("Re", "Re"),
            ("Im", "Im"),
            ("aleph", "aleph"),
            ("prime", "prime"),
            ("dagger", "dagger"),
            ("dagger.double", "ddagger"),
            ("angle.l", "langle"),
            ("angle.r", "rangle"),
            ("ceil.l", "lceil"),
            ("ceil.r", "rceil"),
            ("floor.l", "lfloor"),
            ("floor.r", "rfloor"),
            ("quad", "quad"),
            // Functions (Typst function name → LaTeX command)
            ("arrow", "vec"),
            ("overline", "overline"),
            ("underline", "underline"),
            ("bold", "mathbf"),
            ("italic", "mathit"),
            ("upright", "mathrm"),
            ("cal", "mathcal"),
            ("hat", "hat"),
            ("tilde", "tilde"),
            ("dot", "dot"),
            ("dot.double", "ddot"),
            ("sqrt", "sqrt"),
        ])
    });

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn greek_latex_to_typst() {
        assert_eq!(LATEX_TO_TYPST_COMMANDS.get("alpha"), Some(&"alpha"));
        assert_eq!(LATEX_TO_TYPST_COMMANDS.get("beta"), Some(&"beta"));
        assert_eq!(LATEX_TO_TYPST_COMMANDS.get("Gamma"), Some(&"Gamma"));
    }

    #[test]
    fn operator_latex_to_typst() {
        assert_eq!(LATEX_TO_TYPST_COMMANDS.get("sum"), Some(&"sum"));
        assert_eq!(LATEX_TO_TYPST_COMMANDS.get("int"), Some(&"integral"));
        assert_eq!(LATEX_TO_TYPST_COMMANDS.get("prod"), Some(&"product"));
    }

    #[test]
    fn decoration_latex_to_typst() {
        assert_eq!(LATEX_TO_TYPST_FUNCTIONS.get("hat"), Some(&"hat"));
        assert_eq!(LATEX_TO_TYPST_FUNCTIONS.get("bar"), Some(&"overline"));
        assert_eq!(LATEX_TO_TYPST_FUNCTIONS.get("vec"), Some(&"arrow"));
    }

    #[test]
    fn latex_to_unicode() {
        assert_eq!(LATEX_TO_UNICODE.get("alpha"), Some(&"\u{03B1}"));
        assert_eq!(LATEX_TO_UNICODE.get("infty"), Some(&"\u{221E}"));
    }

    #[test]
    fn environment_mapping() {
        assert_eq!(LATEX_ENV_TO_TYPST.get("pmatrix"), Some(&("mat", "\"(\"")));
        assert_eq!(LATEX_ENV_TO_TYPST.get("bmatrix"), Some(&("mat", "\"[\"")));
        assert_eq!(LATEX_ENV_TO_TYPST.get("cases"), Some(&("cases", "")));
    }

    #[test]
    fn mathbb_mapping() {
        assert_eq!(MATHBB_TO_TYPST.get("R"), Some(&"RR"));
        assert_eq!(MATHBB_TO_TYPST.get("N"), Some(&"NN"));
        assert_eq!(MATHBB_TO_TYPST.get("Z"), Some(&"ZZ"));
    }

    #[test]
    fn reverse_typst_to_latex() {
        assert_eq!(TYPST_TO_LATEX_COMMANDS.get("integral"), Some(&"int"));
        assert_eq!(TYPST_TO_LATEX_COMMANDS.get("product"), Some(&"prod"));
        assert_eq!(TYPST_TO_LATEX_COMMANDS.get("arrow"), Some(&"vec"));
    }
}
